# required for py3.7
dist: xenial
# python versions
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install poetry==0.12.11
  - poetry install
# command to run tests
script: pytest
# combinations to include
after_success:
  - codecov